// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RTE.GestaoUnidadesColaboradores.Infra;

#nullable disable

namespace RTE.GestaoUnidadesColaboradores.Infra.Migrations
{
    [DbContext(typeof(RTEGestaoUnidadesColaboradoresDbContext))]
    partial class RTEGestaoUnidadesColaboradoresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RTE.GestaoUnidadesColaboradores.Domain.Entities.ColaboradorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("RTE.GestaoUnidadesColaboradores.Domain.Entities.UnidadeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("RTE.GestaoUnidadesColaboradores.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RTE.GestaoUnidadesColaboradores.Domain.Entities.ColaboradorEntity", b =>
                {
                    b.HasOne("RTE.GestaoUnidadesColaboradores.Domain.Entities.UnidadeEntity", "Unidade")
                        .WithMany("Colaboradores")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTE.GestaoUnidadesColaboradores.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithOne("Colaborador")
                        .HasForeignKey("RTE.GestaoUnidadesColaboradores.Domain.Entities.ColaboradorEntity", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RTE.GestaoUnidadesColaboradores.Domain.Entities.UnidadeEntity", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("RTE.GestaoUnidadesColaboradores.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("Colaborador")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
